name: Version or publish packages

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Fetch entire Git history so Changesets can generate changelogs.
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: yarn install
      - uses: changesets/action@master
        with:
          publish: yarn run release
          commit: Version packages
          title: Publish packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
